import React from "react";
import { useAdminData } from "../../Hooks/useAdminData";
import {
  FaFilePdf,
  FaChartLine,
  FaUsers,
  FaHospital,
  FaTint,
  FaHistory,
  FaDownload,
} from "react-icons/fa";
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable"; 
import { toast } from "react-toastify";

export default function AdminReports() {
  const { donors, hospitals, requests, history, isLoading } = useAdminData();

const generatePDF = () => {
  const doc = new jsPDF();
const now = new Date();
const dateStr = now.toLocaleDateString("en-GB"); 
const timeStr = now.toLocaleTimeString("en-GB", {
  hour: "2-digit",
  minute: "2-digit",
});

  // إعدادات العناوين
doc.setFontSize(22);
doc.setTextColor(220, 38, 38);
doc.text("BloodLife System Official Report", 14, 20);

doc.setFontSize(10);
doc.setTextColor(100);

doc.text(`Report Date: ${dateStr} | Time: ${timeStr}`, 14, 28);
doc.text("Generated by: Admin Central Engine", 14, 33);
 
  doc.setFontSize(16);
  doc.setTextColor(0);
  doc.text("1. Registered Donors", 14, 45);
  autoTable(doc, {
    startY: 50,
    head: [["Name", "Blood Type", "Age", "Phone", "Email", "Status"]],
    body: donors.map((d) => [
      d.displayName || d.name,
      d.bloodType,
      d.age,
      d.phone,
      d.email,
      d.status,
    ]),
    headStyles: { fillColor: [220, 38, 38] },
  });

  doc.text(
    "2. Medical Entities (Hospitals)",
    14,
    doc.lastAutoTable.finalY + 15,
  );
  autoTable(doc, {
    startY: doc.lastAutoTable.finalY + 20,
    head: [["Hospital Name", "Address", "Phone", "Email"]],
    body: hospitals.map((h) => [
      h.displayName || h.name,
      h.hospitalAddress || h.address,
      h.phone,
      h.email,
    ]),
    headStyles: { fillColor: [37, 99, 235] },
  });
  doc.text("3. Recent Blood Requests", 14, doc.lastAutoTable.finalY + 15);
  autoTable(doc, {
    startY: doc.lastAutoTable.finalY + 20,
    head: [["Hospital", "Blood Type", "Quantity", "Status"]],
    body: requests.map((r) => [
      r.hospitalName,
      r.bloodTypeNeeded,
      r.quantity,
      r.status,
    ]),
    headStyles: { fillColor: [234, 88, 12] },
  });
  doc.text("3. Recent Blood History", 14, doc.lastAutoTable.finalY + 15);
  autoTable(doc, {
    startY: doc.lastAutoTable.finalY + 20,
    head: [["Hospital", "Donor", "Blood Type", "Date", "Status"]],
    body: history.map((r) => [
      r.hospitalName,
      r.donorName,
      r.bloodTypeNeeded,
      r.updatedAt,
      r.status,
    ]),
    headStyles: { fillColor: [100, 70, 12] },
  });

  doc.save(`BloodLife_Report.pdf`);
  toast.success("PDF Report generated!");
};
 if (isLoading)
   return (
     <div className="h-screen flex flex-col items-center justify-center gap-4">
       <div className="w-12 h-12 border-4 border-red-500 border-t-transparent rounded-full animate-spin"></div>
       <p className="text-gray-500 font-medium tracking-widest uppercase text-xs">
         Loading....
       </p>
     </div>
   );

  return (
    <div className="p-6min-h-screen">
      <div className="max-w-6xl mx-auto">
          <button
            onClick={generatePDF}
            className="flex items-center gap-3 px-4 py-4 bg-red-600 text-white rounded-2xl font-bold hover:bg-red-700 transition-all  active:scale-95"
          >
            <FaDownload /> Export PDF Report
          </button>
        </div>
   
      </div>

  );
}
